<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ScopeDefinition" nsURI="http://mondo.org/ScopeDefinition" nsPrefix="def">
  <eClassifiers xsi:type="ecore:EClass" name="MetaModelScope">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopeRules" upperBound="-1"
        eType="#//ScopeRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScopeRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClass" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scopeDefinition" eType="#//ScopeDefinitionEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eReference" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScopeDefinitionEnum">
    <eLiterals name="SAME_WORKSPACE" value="3" literal="SAME_WORKSPACE"/>
    <eLiterals name="SAME_PROJECT" value="2" literal="SAME_PROJECT"/>
    <eLiterals name="SAME_PACKAGE" value="1"/>
    <eLiterals name="SAME_UNIT"/>
  </eClassifiers>
</ecore:EPackage>
